Added flows:
NitsanAmit/TenQ pull request #21
Opened 2021-09-11 10:42 UTC by roykreiner-s

1. close room option
2. delete room option
3. export room option (exports the playlist to spotify library)

- removed users list action button from settings

2021-09-15 16:00 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/ui/activities/ExistingRoomsActivity.java
> +                HashMap<String, Object> bodyDetails = new HashMap<>(1);
Use generic Map:
`Map<String, Object> body = new HashMap<>();`

2021-09-15 16:04 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/ui/activities/ExistingRoomsActivity.java
> +                                Log.e("ExistingRoomsActivity", t.getMessage(), t);
Maybe add a toast "Error saving playlist"?

2021-09-15 16:05 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/network/SpotifyApiService.java
> +    Call<Void> followPlaylist(@Path("playlist_id") String playlistId, @Body() Map<String, Object> details);
I'm thinking about the flow of room for guests.... I think when joining a room, this api should be called, no?
And when clicking "export", a new identical playlist should be created.
If the user just follows, the playlist might change if the host manually changes it in his Spotify account. What do you think?

2021-09-15 16:06 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/ui/activities/ExistingRoomsActivity.java
> +                if (!room.getHost().getId().equals(getAuthService().getCurrentUser().getId())){
Let's hide the "close" button for guests, so it's not even an option? I think it's a better experience :)

2021-09-15 16:07 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/ui/activities/ExistingRoomsActivity.java
> +                else if (!room.isActive()) {
Same here, the "close" button should be hidden if the room is not active

2021-09-15 16:08 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/ui/activities/ExistingRoomsActivity.java
> +                    View view = inflater.inflate(R.layout.dialog_close_room, null);
Why do you need a custom view for the dialog?
Use the dialog builder "setMessage" and "setTitle" functions:
![image](https://user-images.githubusercontent.com/29373422/133469450-e2a290ef-b3cf-4fe1-982e-d5b8dc4817f6.png)

2021-09-15 16:11 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/ui/activities/ExistingRoomsActivity.java
> +    private final MutableLiveData<ViewModelError> error = new MutableLiveData<>(null);
Please move these and all network communication to a viewmodel class, like in JoinActivityViewModel

2021-09-15 16:12 UTC, NitsanAmit commented on app/src/main/java/com/postpc/tenq/ui/activities/RoomActivity.java
> +    private TracksAdapter adapter;
Why?

2021-09-15 16:16 UTC, NitsanAmit requested changes, later dismissed
Nice!
Let me know if you wanna talk about the follow/export following.
Right now the playlist is created when the room is created, and it is public and collaborative. I think that **guests should automatically follow the playlist when they join the room, and "unfollow" when they leave.**
**Exporting** should create a new, identical playlist, private only to the user who exported it - so it sort of "freezes" the room playlist at that moment and creates a private copy of it.

2021-09-17 11:15 UTC, roykreiner-s commented
Megre.

2021-09-17 11:25 UTC, NitsanAmit approved these changes

2021-09-17 11:30 UTC, merged